FROM tomcat:9-jre8-alpine
#FROM tomcat:9-jre8

WORKDIR /usr/local/tomcat/webapps

#RUN rm -rf ./manager
#RUN rm -rf ./host-manager
#RUN rm -rf ./ROOT
#RUN rm -rf ./examples
#RUN rm -rf ./docs

#Exploded Folder
COPY war/FAPServer.war ./

#funktioniert noch nicht
#WORKDIR /usr/local/tomcat
#COPY conf/ ./

ENV JAVA_OPTS -Xms1024m -Xmx3800m

EXPOSE 8080
