#FROM tomcat:9-jre8-alpine
FROM tomcat:9-jre11
ADD conf/tomcat-users.xml /usr/local/tomcat/conf/
RUN bash -c 'mkdir -pv /usr/local/tomee/conf/'
RUN echo '<?xml version="1.0" encoding="utf-8"?><tomcat-users><role rolename="tomee-admin"/><user username="tomee" password="tomee" roles="tomee-admin,manager-gui,manager-script"/></tomcat-users>' > /usr/local/tomee/conf/tomcat-users.xml

WORKDIR /usr/local/tomcat/webapps

#RUN rm -rf ./manager
#RUN rm -rf ./host-manager
#RUN rm -rf ./ROOT
#RUN rm -rf ./examples
#RUN rm -rf ./docs

#Exploded Folder
COPY war/FAPServer.war ./

ADD war/angular/ ./angular

#funktioniert noch nicht
#WORKDIR /usr/local/tomcat
#COPY conf/ ./

ENV JAVA_OPTS -Xms1024m -Xmx3800m

EXPOSE 8080
